# 02 - Candidate Variable Acquisition
Main goal: Use our raw data to calculate our candidate variables

In [121]:
import pandas as pd
import numpy as np
import os
# from scipy.stats import mstats

In [122]:
#Loading SPX return data
spx = pd.read_csv('data/raw/01_spx_returns.csv')
spx = spx[['Date', 'Returns']]
spx

            Date   Returns
0     1990-01-03 -0.002586
1     1990-01-04 -0.008613
2     1990-01-05 -0.009756
3     1990-01-08  0.004514
4     1990-01-09 -0.011787
...          ...       ...
9168  2026-06-01  0.002625
9169  2026-06-02  0.001292
9170  2026-06-03 -0.007372
9171  2026-06-04  0.004055
9172  2026-06-05 -0.026445

[9173 rows x 2 columns]

In [123]:
#Return-based volatility and downside-risk variables

#Annualized square return
spx['r2_ann'] = (spx['Returns']**2)*252
# spx['r2_ann_winsorized'] = mstats.winsorize(spx['r2_ann'], limits=[0.0, 0.005])

#Rolling RV
for window in [5, 21, 63, 126, 252]:
    spx[f'RV_{window}'] = spx['r2_ann'].rolling(window).mean()

#EWMA
for lam in [0.94, 0.97, 0.985]:
    spx[f'EWMA_lam_{lam}'] = spx['r2_ann'].ewm(alpha = 1-lam, adjust = False).mean()

#Downside RV
spx['RV_down'] = spx['r2_ann'].where(spx['Returns'] < 0, 0)
for window in [5, 21, 63]: 
    spx[f'RV_down_{window}'] = spx['RV_down'].rolling(window).mean()

#Return-shape controls
spx['abs_ret_norm'] = spx['Returns'].abs() * np.sqrt(252)
spx['neg_ret_dummy'] = np.where(spx['Returns'] < 0, 1, 0)
spx['neg_ret_mag'] = spx['Returns'].where(spx['Returns'] < 0, 0).abs()
spx.to_csv('data/processed/SPX_transformed.csv', index=False)
spx

,Date,Returns,r2_ann,RV_5,RV_21,RV_63,RV_126,RV_252,EWMA_lam_0.94,EWMA_lam_0.97,EWMA_lam_0.985,RV_down,RV_down_5,RV_down_21,RV_down_63,abs_ret_norm,neg_ret_dummy,neg_ret_mag
0,1990-01-03,-0.002586,0.001685,NaN,NaN,NaN,NaN,NaN,0.001685,0.001685,0.001685,0.001685,NaN,NaN,NaN,0.041044,1,0.002586
1,1990-01-04,-0.008613,0.018694,NaN,NaN,NaN,NaN,NaN,0.002705,0.002195,0.001940,0.018694,NaN,NaN,NaN,0.136727,1,0.008613
2,1990-01-05,-0.009756,0.023986,NaN,NaN,NaN,NaN,NaN,0.003982,0.002849,0.002270,0.023986,NaN,NaN,NaN,0.154875,1,0.009756
3,1990-01-08,0.004514,0.005136,NaN,NaN,NaN,NaN,NaN,0.004051,0.002917,0.002313,0.000000,NaN,NaN,NaN,0.071665,0,0.000000
4,1990-01-09,-0.011787,0.035009,0.016902,NaN,NaN,NaN,NaN,0.005909,0.003880,0.002804,0.035009,0.015875,NaN,NaN,0.187108,1,0.011787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9168,2026-06-01,0.002625,0.001737,0.004136,0.010819,0.021278,0.016274,0.014290,0.012726,0.016233,0.017873,0.000000,0.000000,0.002778,0.007701,0.041675,0,0.000000
9169,2026-06-02,0.001292,0.000421,0.002339,0.010736,0.020928,0.016220,0.014292,0.011987,0.015758,0.017611,0.000000,0.000000,0.002778,0.007344,0.020511,0,0.000000
9170,2026-06-03,-0.007372,0.013695,0.005077,0.011190,0.020904,0.016272,0.014329,0.012090,0.015697,0.017552,0.013695,0.002739,0.003232,0.007561,0.117028,1,0.007372
9171,2026-06-04,0.004055,0.004144,0.004237,0.010596,0.020843,0.016293,0.014312,0.011613,0.015350,0.017351,0.000000,0.002739,0.003232,0.007434,0.064371,0,0.000000
9172,2026-06-05,-0.026445,0.176238,0.039247,0.016435,0.022935,0.017674,0.015011,0.021490,0.020177,0.019734,0.176238,0.037987,0.011625,0.009526,0.419807,1,0.026445

In [124]:
#Market liquidity and trading frictions
df = pd.read_csv('data/raw/01_spx_returns.csv', parse_dates=['Date'])
df = df[['Date', 'Close', 'Volume', 'Returns']]

#SPX dollar volume
df['dollar_vol'] = df['Close'] * df['Volume']

#Rolling volume growth using the past 21 days
df['vol_growth'] = df['dollar_vol'].pct_change()
df['rolling_vol_growth'] = df['vol_growth'].rolling(21).mean()

#Amihud illiquidity and rolling 21 day amihud
df['amihud_illiquidity'] = df['Returns'].abs()/df['dollar_vol']
df['rolling_amihud'] = df['amihud_illiquidity'].rolling(21).mean()

df.to_csv('data/processed/liquidity.csv', index=False)
df

,Date,Close,Volume,Returns,dollar_vol,vol_growth,rolling_vol_growth,amihud_illiquidity,rolling_amihud
0,1990-01-03,358.760010,192330000,-0.002586,6.900031e+10,NaN,NaN,3.747142e-14,NaN
1,1990-01-04,355.670013,177000000,-0.008613,6.295359e+10,-0.087633,NaN,1.368149e-13,NaN
2,1990-01-05,352.200012,158530000,-0.009756,5.583427e+10,-0.113088,NaN,1.747357e-13,NaN
3,1990-01-08,353.790009,140110000,0.004514,4.956952e+10,-0.112203,NaN,9.107351e-14,NaN
4,1990-01-09,349.619995,155210000,-0.011787,5.426452e+10,0.094715,NaN,2.172081e-13,NaN
...,...,...,...,...,...,...,...,...,...
9168,2026-06-01,7599.959961,6583960000,0.002625,5.003783e+13,-0.159964,0.017065,5.246622e-17,1.281703e-16
9169,2026-06-02,7609.779785,5904410000,0.001292,4.493126e+13,-0.102054,0.019378,2.875702e-17,1.255610e-16
9170,2026-06-03,7553.680176,5753860000,-0.007372,4.346282e+13,-0.032682,0.014414,1.696172e-16,1.284872e-16
9171,2026-06-04,7584.310059,5398910000,0.004055,4.094701e+13,-0.057884,0.010679,9.902950e-17,1.231143e-16
9172,2026-06-05,7383.740234,5591290000,-0.026445,4.128463e+13,0.008245,-0.001518,6.405619e-16,1.392820e-16

In [125]:
#Loading FRED data
fred_raw = pd.read_csv('data/raw/02_fred_raw.csv', parse_dates=['Date'])
spx = pd.read_csv('data/raw/01_spx_returns.csv', parse_dates=['Date'])
spx = spx[['Date']].copy()

#Linking FRED data to SPX trading days using merge_asof to avoid look ahead bias
fred = pd.merge_asof(
    spx.sort_values('Date'),
    fred_raw.sort_values('Date'),
    on='Date'
)

fred

,Date,BAA,AAA,HY_OAS,IG_OAS,TED,SOFR,DGS3MO,DGS2,DGS10,DTB3
0,1990-01-03,9.86,8.90,NaN,NaN,0.75,NaN,7.89,7.94,7.99,7.63
1,1990-01-04,9.84,8.89,NaN,NaN,0.79,NaN,7.84,7.92,7.98,7.59
2,1990-01-05,9.88,8.88,NaN,NaN,0.84,NaN,7.79,7.90,7.99,7.54
3,1990-01-08,9.88,8.90,NaN,NaN,0.84,NaN,7.79,7.90,8.02,7.54
4,1990-01-09,9.86,8.92,NaN,NaN,0.76,NaN,7.80,7.91,8.02,7.55
...,...,...,...,...,...,...,...,...,...,...,...
9168,2026-06-01,6.01,5.49,2.72,0.73,0.09,3.65,3.78,4.05,4.47,3.63
9169,2026-06-02,6.00,5.48,2.71,0.74,0.09,3.63,3.77,4.05,4.46,3.63
9170,2026-06-03,6.03,5.51,2.75,0.74,0.09,3.61,3.78,4.08,4.49,3.63
9171,2026-06-04,6.01,5.49,2.74,0.74,0.09,3.62,3.78,4.05,4.47,3.63
9172,2026-06-05,6.01,5.49,2.74,0.74,0.09,3.62,3.78,4.05,4.47,3.63

In [126]:
#Transforming FRED data

#Investment grade and high yield credit spread
fred['baa_aaa'] = fred['BAA'] - fred['AAA']

#Daily change in credit spreads and absolute change
fred['baa_aaa_change'] = fred['baa_aaa'].diff()
fred['baa_aaa_change_abs'] = fred['baa_aaa_change'].abs()
fred['HY_OAS_change'] = fred['HY_OAS'].diff()
fred['HY_OAS_change_abs'] = fred['HY_OAS_change'].abs()
fred['IG_OAS_change'] = fred['IG_OAS'].diff()
fred['IG_OAS_change_abs'] = fred['IG_OAS_change'].abs()

#SOFR spread
fred['SOFR_spread'] = fred['SOFR'] - fred['DTB3']

#Yield slope (10y-2y)
fred['yield_slope'] = fred['DGS10'] - fred['DGS2']

#Treasury yield curvature using butterfly spread
fred['yield_curv'] = 2 * fred['DGS2'] - fred['DGS3MO'] - fred['DGS10']

#Rolling RV over 5, 21, 63, 126, and 252 trading days of daily changes in 10y and 2y
fred['d_DGS2'] = fred['DGS2'].diff()
fred['d_DGS10'] = fred['DGS10'].diff()
for window in [5, 21, 63, 126, 252]:
    fred[f'RV_rate_2y_{window}']  = (fred['d_DGS2']**2).rolling(window, min_periods=1).mean()
    fred[f'RV_rate_10y_{window}'] = (fred['d_DGS10']**2).rolling(window, min_periods=1).mean()

fred.to_csv('data/processed/FRED_transformed.csv', index=False)
fred

,Date,BAA,AAA,HY_OAS,IG_OAS,TED,SOFR,DGS3MO,DGS2,DGS10,...,RV_rate_2y_5,RV_rate_10y_5,RV_rate_2y_21,RV_rate_10y_21,RV_rate_2y_63,RV_rate_10y_63,RV_rate_2y_126,RV_rate_10y_126,RV_rate_2y_252,RV_rate_10y_252
0,1990-01-03,9.86,8.90,NaN,NaN,0.75,NaN,7.89,7.94,7.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1990-01-04,9.84,8.89,NaN,NaN,0.79,NaN,7.84,7.92,7.98,...,0.000400,0.000100,0.000400,0.000100,0.000400,0.000100,0.000400,0.000100,0.000400,0.000100
2,1990-01-05,9.88,8.88,NaN,NaN,0.84,NaN,7.79,7.90,7.99,...,0.000400,0.000100,0.000400,0.000100,0.000400,0.000100,0.000400,0.000100,0.000400,0.000100
3,1990-01-08,9.88,8.90,NaN,NaN,0.84,NaN,7.79,7.90,8.02,...,0.000267,0.000367,0.000267,0.000367,0.000267,0.000367,0.000267,0.000367,0.000267,0.000367
4,1990-01-09,9.86,8.92,NaN,NaN,0.76,NaN,7.80,7.91,8.02,...,0.000225,0.000275,0.000225,0.000275,0.000225,0.000275,0.000225,0.000275,0.000225,0.000275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9168,2026-06-01,6.01,5.49,2.72,0.73,0.09,3.65,3.78,4.05,4.47,...,0.003920,0.001060,0.002929,0.002357,0.002717,0.002178,0.001971,0.001702,0.002189,0.001706
9169,2026-06-02,6.00,5.48,2.71,0.74,0.09,3.63,3.77,4.05,4.46,...,0.001040,0.000360,0.002929,0.002357,0.002692,0.002178,0.001968,0.001700,0.002186,0.001704
9170,2026-06-03,6.03,5.51,2.75,0.74,0.09,3.61,3.78,4.08,4.49,...,0.001200,0.000460,0.002738,0.002229,0.002692,0.002178,0.001937,0.001668,0.002179,0.001698
9171,2026-06-04,6.01,5.49,2.74,0.74,0.09,3.62,3.78,4.05,4.47,...,0.001360,0.000360,0.002762,0.002229,0.002692,0.002159,0.001937,0.001671,0.002181,0.001700
9172,2026-06-05,6.01,5.49,2.74,0.74,0.09,3.62,3.78,4.05,4.47,...,0.001340,0.000360,0.002590,0.001995,0.002690,0.002152,0.001933,0.001664,0.002149,0.001667

In [127]:
#Loading yfinance data
yf_raw = pd.read_csv('data/raw/03_yf_raw.csv', parse_dates=['Date'])

#Linking yfinance data to SPX trading days using merge_asof to avoid look ahead bias
yf = pd.merge_asof(
    spx.sort_values('Date'),
    yf_raw.sort_values('Date'),
    on='Date'
)
yf

,Date,HYG,LQD,XLF,WTI,USD,GOLD
0,1990-01-03,NaN,NaN,NaN,NaN,94.419998,NaN
1,1990-01-04,NaN,NaN,NaN,NaN,92.519997,NaN
2,1990-01-05,NaN,NaN,NaN,NaN,92.849998,NaN
3,1990-01-08,NaN,NaN,NaN,NaN,92.050003,NaN
4,1990-01-09,NaN,NaN,NaN,NaN,92.349998,NaN
...,...,...,...,...,...,...,...
9168,2026-06-01,79.839996,108.930000,51.430000,92.160004,99.199997,4475.200195
9169,2026-06-02,79.900002,108.919998,51.459999,93.760002,99.220001,4489.100098
9170,2026-06-03,79.680000,108.620003,50.869999,96.019997,99.529999,4436.700195
9171,2026-06-04,79.830002,108.849998,52.189999,93.040001,99.410004,4475.799805
9172,2026-06-05,79.430000,108.169998,52.299999,90.540001,100.070000,4337.100098

In [128]:
#Transforming yfinance data

#Getting returns for each series for RV calculation
for col in ['HYG', 'LQD', 'XLF', 'WTI', 'USD', 'GOLD']:
    yf[f'{col}_ret'] = yf[col].pct_change()

#Calculating RV over 5, 21, 63, 126, and 252 trading days
for col in ['HYG', 'LQD', 'XLF', 'WTI', 'USD', 'GOLD']:
    for window in [5, 21, 63, 126, 252]:
        yf[f'{col}_RV{window}'] = (yf[f'{col}_ret']**2 * 252).rolling(window).mean()

yf.to_csv('data/processed/yf_transformed.csv', index=False)
yf

,Date,HYG,LQD,XLF,WTI,USD,GOLD,HYG_ret,LQD_ret,XLF_ret,...,USD_RV5,USD_RV21,USD_RV63,USD_RV126,USD_RV252,GOLD_RV5,GOLD_RV21,GOLD_RV63,GOLD_RV126,GOLD_RV252
0,1990-01-03,NaN,NaN,NaN,NaN,94.419998,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1990-01-04,NaN,NaN,NaN,NaN,92.519997,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1990-01-05,NaN,NaN,NaN,NaN,92.849998,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1990-01-08,NaN,NaN,NaN,NaN,92.050003,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1990-01-09,NaN,NaN,NaN,NaN,92.349998,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9168,2026-06-01,79.839996,108.930000,51.430000,92.160004,99.199997,4475.200195,-0.000764,-0.000156,-0.002908,...,0.000803,0.001744,0.003371,0.003101,0.003512,0.041804,0.038684,0.079578,0.104318,0.071848
9169,2026-06-02,79.900002,108.919998,51.459999,93.760002,99.220001,4489.100098,0.000752,-0.000092,0.000583,...,0.000691,0.001724,0.003185,0.003097,0.003512,0.041244,0.038669,0.074626,0.104012,0.071786
9170,2026-06-03,79.680000,108.620003,50.869999,96.019997,99.529999,4436.700195,-0.002753,-0.002754,-0.011465,...,0.001174,0.001757,0.003192,0.003116,0.003482,0.041147,0.033481,0.075146,0.104235,0.071305
9171,2026-06-04,79.830002,108.849998,52.189999,93.040001,99.410004,4475.799805,0.001883,0.002117,0.025948,...,0.001063,0.001774,0.003074,0.003119,0.003452,0.038225,0.033639,0.074997,0.104081,0.071346
9172,2026-06-05,79.430000,108.169998,52.299999,90.540001,100.070000,4337.100098,-0.005011,-0.006247,0.002108,...,0.003222,0.002041,0.003206,0.003154,0.003475,0.077299,0.035969,0.077820,0.105983,0.072258

In [129]:
#Loading EPU data
epu = pd.read_csv('data/raw/EPU_index.csv')

#Assigning proper date format
epu['Date'] = pd.to_datetime(epu[['year', 'month', 'day']])
epu = epu[['Date', 'daily_policy_index']].copy()
epu = epu[epu['Date'] >= '1996-01-01'].reset_index(drop=True)

#Aligning dates to SPX trading days
epu = pd.merge_asof(
    spx.sort_values('Date'),
    epu.sort_values('Date'),
    on='Date'
)
epu.columns = ['Date', 'EPU']
epu.to_csv('data/processed/EPU.csv', index=False)
epu

           Date     EPU
0    1990-01-03     NaN
1    1990-01-04     NaN
2    1990-01-05     NaN
3    1990-01-08     NaN
4    1990-01-09     NaN
...         ...     ...
9168 2026-06-01  242.92
9169 2026-06-02  221.12
9170 2026-06-03  468.63
9171 2026-06-04  379.17
9172 2026-06-05  244.31

[9173 rows x 2 columns]

In [130]:
#Loading GPR data
gpr = pd.read_excel('data/raw/GPR_index.xls')

#Assigning proper date format
gpr = gpr[['month', 'GPR']].copy()
gpr.columns = ['Date', 'GPR']
gpr['Date'] = pd.to_datetime(gpr['Date'])
gpr = gpr[gpr['Date'] >= '1996-01-01'].reset_index(drop=True)

#Aligning to SPX trading days
gpr = pd.merge_asof(
    spx.sort_values('Date'),
    gpr.sort_values('Date'),
    on='Date'
)
gpr.to_csv('data/processed/GPR.csv', index=False)
gpr

           Date         GPR
0    1990-01-03         NaN
1    1990-01-04         NaN
2    1990-01-05         NaN
3    1990-01-08         NaN
4    1990-01-09         NaN
...         ...         ...
9168 2026-06-01  184.177048
9169 2026-06-02  184.177048
9170 2026-06-03  184.177048
9171 2026-06-04  184.177048
9172 2026-06-05  184.177048

[9173 rows x 2 columns]

In [131]:
# Combining all the data and creating the final CSV file

# CHOOSE V_proxy VARIABLE
ANCHOR = 'EWMA_lam_0.94' #Used this as V_proxy for now

# Columns to drop entirely
cols_to_drop = ['Returns', 'r2_ann', 'BAA', 'AAA', 'DTB3', 'SOFR',
                'd_DGS2', 'd_DGS10', 'HYG', 'LQD', 'XLF', 'WTI', 'USD', 'GOLD',
                'vol_growth', 'HYG_ret', 'LQD_ret', 'XLF_ret',
                'WTI_ret', 'USD_ret', 'GOLD_ret']

# Columns to not standardize
do_not_standardize = ['Date', 'neg_ret_dummy', ANCHOR]

# Build merged DataFrame
base = pd.read_csv('data/processed/SPX_transformed.csv', parse_dates=['Date'])
liq = df.drop(columns=['Close', 'Volume', 'Returns'])
merged = base.merge(liq, on='Date', how='left')
merged = merged.merge(fred, on='Date', how='left')
merged = merged.merge(yf, on='Date', how='left')
merged = merged.merge(epu, on='Date', how='left')
merged = merged.merge(gpr, on='Date', how='left')

# Save raw version
merged.to_csv('data/processed/all_variables_raw.csv', index=False)

# Drop unwanted columns
merged_std = merged.drop(columns=cols_to_drop)

# Rename anchor to V_proxy and move to front
merged_std = merged_std.rename(columns={ANCHOR: 'V_proxy'})
do_not_standardize = ['Date', 'neg_ret_dummy', 'V_proxy']

# Standardize all candidate X columns
cols_to_standardize = [col for col in merged_std.columns if col not in do_not_standardize]

for col in cols_to_standardize:
    rolling_mean = merged_std[col].expanding().mean()
    rolling_std = merged_std[col].expanding().std()
    rolling_std = rolling_std.replace(0, float('nan'))
    merged_std[col] = (merged_std[col] - rolling_mean) / rolling_std

# Reorder so Date and V_proxy come first
cols_ordered = ['Date', 'V_proxy'] + [c for c in merged_std.columns if c not in ['Date', 'V_proxy']]
merged_std = merged_std[cols_ordered]
#Filtering for dates from 1996 and onwards
merged_std = merged_std[merged_std['Date'] >= '1996-01-01'].reset_index(drop=True)

merged_std.to_csv('data/processed/all_variables_standardized.csv', index=False)
print(f'Anchor: {ANCHOR} → saved as V_proxy')
print(f'Shape: {merged_std.shape}')
merged_std

Anchor: EWMA_lam_0.94 → saved as V_proxy
Shape: (7657, 78)

,Date,V_proxy,RV_5,RV_21,RV_63,RV_126,RV_252,EWMA_lam_0.97,EWMA_lam_0.985,RV_down,...,USD_RV63,USD_RV126,USD_RV252,GOLD_RV5,GOLD_RV21,GOLD_RV63,GOLD_RV126,GOLD_RV252,EPU,GPR
0,1996-01-02,0.009068,-0.596398,-0.234815,-0.611063,-0.812564,-0.897126,-0.579839,-0.740683,-0.305537,...,-1.499857,-0.832213,-0.017600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996-01-03,0.008538,-0.643239,-0.241878,-0.610880,-0.811881,-0.898081,-0.607447,-0.754517,-0.305427,...,-1.484003,-0.819184,-0.009318,NaN,NaN,NaN,NaN,NaN,-0.707107,NaN
2,1996-01-04,0.008539,-0.527872,-0.343639,-0.596252,-0.840234,-0.892719,-0.604591,-0.751420,0.121453,...,-1.481153,-0.817848,-0.014386,NaN,NaN,NaN,NaN,NaN,-0.850655,NaN
3,1996-01-05,0.008065,-0.520419,-0.389773,-0.596614,-0.843627,-0.891801,-0.629943,-0.764233,-0.273195,...,-1.528515,-0.842807,-0.034115,NaN,NaN,NaN,NaN,NaN,-1.071704,NaN
4,1996-01-08,0.007703,-0.522362,-0.399280,-0.592720,-0.841664,-0.890044,-0.649595,-0.774066,-0.305410,...,-1.547015,-0.842342,-0.110046,NaN,NaN,NaN,NaN,NaN,0.136508,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7652,2026-06-01,0.012726,-0.363014,-0.339403,-0.220624,-0.386568,-0.544512,-0.336704,-0.365432,-0.193956,...,-0.756788,-0.925340,-0.943205,0.204660,0.208140,1.766859,3.197793,2.209305,1.281650,1.563603
7653,2026-06-02,0.011987,-0.386006,-0.340681,-0.227467,-0.387818,-0.544424,-0.346559,-0.372021,-0.193945,...,-0.804886,-0.926365,-0.943177,0.193382,0.207696,1.584030,3.181628,2.204893,1.059021,1.563251
7654,2026-06-03,0.012090,-0.350904,-0.333546,-0.227909,-0.386566,-0.543282,-0.347827,-0.373481,-0.029504,...,-0.802974,-0.920769,-0.953280,0.191425,0.053916,1.602732,3.188566,2.177994,3.581750,1.562899
7655,2026-06-04,0.011613,-0.361643,-0.342829,-0.229106,-0.386050,-0.543748,-0.355022,-0.378538,-0.193942,...,-0.833620,-0.919980,-0.963090,0.132649,0.058591,1.596795,3.179067,2.179197,2.668054,1.562548
7656,2026-06-05,0.021490,0.086998,-0.251349,-0.188111,-0.353429,-0.523165,-0.254500,-0.318311,1.921858,...,-0.799203,-0.909628,-0.955419,0.918273,0.127658,1.700245,3.259112,2.227208,1.293125,1.562197